/* tslint:disable */
/* eslint-disable */
/**
 * bartender
 * Job middleware for i-VRESSE
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BearerResponse
 */
export interface BearerResponse {
    /**
     * 
     * @type {string}
     * @memberof BearerResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof BearerResponse
     */
    tokenType: string;
}

/**
 * Check if a given object implements the BearerResponse interface.
 */
export function instanceOfBearerResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "tokenType" in value;

    return isInstance;
}

export function BearerResponseFromJSON(json: any): BearerResponse {
    return BearerResponseFromJSONTyped(json, false);
}

export function BearerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BearerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
    };
}

export function BearerResponseToJSON(value?: BearerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'token_type': value.tokenType,
    };
}

