/* tslint:disable */
/* eslint-disable */
/**
 * bartender
 * Job middleware for i-VRESSE
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Detail } from "./Detail";
import { DetailFromJSON, DetailFromJSONTyped, DetailToJSON } from "./Detail";

/**
 *
 * @export
 * @interface ErrorModel
 */
export interface ErrorModel {
  /**
   *
   * @type {Detail}
   * @memberof ErrorModel
   */
  detail: Detail;
}

/**
 * Check if a given object implements the ErrorModel interface.
 */
export function instanceOfErrorModel(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "detail" in value;

  return isInstance;
}

export function ErrorModelFromJSON(json: any): ErrorModel {
  return ErrorModelFromJSONTyped(json, false);
}

export function ErrorModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ErrorModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    detail: DetailFromJSON(json["detail"]),
  };
}

export function ErrorModelToJSON(value?: ErrorModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    detail: DetailToJSON(value.detail),
  };
}
