/* tslint:disable */
/* eslint-disable */
/**
 * bartender
 * Job middleware for i-VRESSE
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * DTO for social providers name of a user.
 * @export
 * @interface OAuthAccountName
 */
export interface OAuthAccountName {
  /**
   *
   * @type {string}
   * @memberof OAuthAccountName
   */
  oauthName: string;
  /**
   *
   * @type {string}
   * @memberof OAuthAccountName
   */
  accountId: string;
  /**
   *
   * @type {string}
   * @memberof OAuthAccountName
   */
  accountEmail: string;
}

/**
 * Check if a given object implements the OAuthAccountName interface.
 */
export function instanceOfOAuthAccountName(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "oauthName" in value;
  isInstance = isInstance && "accountId" in value;
  isInstance = isInstance && "accountEmail" in value;

  return isInstance;
}

export function OAuthAccountNameFromJSON(json: any): OAuthAccountName {
  return OAuthAccountNameFromJSONTyped(json, false);
}

export function OAuthAccountNameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OAuthAccountName {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    oauthName: json["oauth_name"],
    accountId: json["account_id"],
    accountEmail: json["account_email"],
  };
}

export function OAuthAccountNameToJSON(value?: OAuthAccountName | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    oauth_name: value.oauthName,
    account_id: value.accountId,
    account_email: value.accountEmail,
  };
}
