/* tslint:disable */
/* eslint-disable */
/**
 * bartender
 * Job middleware for i-VRESSE
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuth2AuthorizeResponse
 */
export interface OAuth2AuthorizeResponse {
    /**
     * 
     * @type {string}
     * @memberof OAuth2AuthorizeResponse
     */
    authorizationUrl: string;
}

/**
 * Check if a given object implements the OAuth2AuthorizeResponse interface.
 */
export function instanceOfOAuth2AuthorizeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authorizationUrl" in value;

    return isInstance;
}

export function OAuth2AuthorizeResponseFromJSON(json: any): OAuth2AuthorizeResponse {
    return OAuth2AuthorizeResponseFromJSONTyped(json, false);
}

export function OAuth2AuthorizeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2AuthorizeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorizationUrl': json['authorization_url'],
    };
}

export function OAuth2AuthorizeResponseToJSON(value?: OAuth2AuthorizeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorization_url': value.authorizationUrl,
    };
}

