/* tslint:disable */
/* eslint-disable */
/**
 * bartender
 * Job middleware for i-VRESSE
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * DTO to create user.
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserCreate
   */
  password: string;
  /**
   *
   * @type {boolean}
   * @memberof UserCreate
   */
  isActive?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserCreate
   */
  isSuperuser?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserCreate
   */
  isVerified?: boolean;
}

/**
 * Check if a given object implements the UserCreate interface.
 */
export function instanceOfUserCreate(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "email" in value;
  isInstance = isInstance && "password" in value;

  return isInstance;
}

export function UserCreateFromJSON(json: any): UserCreate {
  return UserCreateFromJSONTyped(json, false);
}

export function UserCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserCreate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
    isActive: !exists(json, "is_active") ? undefined : json["is_active"],
    isSuperuser: !exists(json, "is_superuser")
      ? undefined
      : json["is_superuser"],
    isVerified: !exists(json, "is_verified") ? undefined : json["is_verified"],
  };
}

export function UserCreateToJSON(value?: UserCreate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
    is_active: value.isActive,
    is_superuser: value.isSuperuser,
    is_verified: value.isVerified,
  };
}
