FROM alpine:3.19

RUN apk add --no-cache openssl

CMD (test -e private_key.pem || openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048) && \
    (test -e public_key.pem || openssl rsa -pubout -in private_key.pem -out public_key.pem) && \
    (test -e session.secret || openssl rand -hex 32 > session.secret) && \
    chmod +r /certs/private_key.pem
