# TODO get image with haddock3 from somewhere
FROM ghcr.io/haddocking/haddock3:latest as haddock3

# TODO publish image
FROM ghcr.io/ivresse/bartender:latest

COPY --from=haddock3 /usr/local/bin/haddock3 /usr/local/bin/haddock3
