/* tslint:disable */
/* eslint-disable */
/**
 * bartender
 * Job middleware for i-VRESSE
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  HTTPValidationError,
  UserAsListItem,
  UserProfileInputDTO,
  UserRead,
  UserUpdate,
} from '../models';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UserAsListItemFromJSON,
    UserAsListItemToJSON,
    UserProfileInputDTOFromJSON,
    UserProfileInputDTOToJSON,
    UserReadFromJSON,
    UserReadToJSON,
    UserUpdateFromJSON,
    UserUpdateToJSON,
} from '../models';

export interface ListUsersApiUsersGetRequest {
    limit?: number;
    offset?: number;
}

export interface UsersDeleteUserUsersIdDeleteRequest {
    id: any;
}

export interface UsersPatchCurrentUserUsersMePatchRequest {
    userUpdate: UserUpdate;
}

export interface UsersPatchUserUsersIdPatchRequest {
    id: any;
    userUpdate: UserUpdate;
}

export interface UsersUserUsersIdGetRequest {
    id: any;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * List of users.  Requires super user powers.  Args:     limit: Number of users to return. Defaults to 50.     offset: Offset. Defaults to 0.     super_user: Check if current user is super.     user_db: User db.  Returns:     List of users.
     * List Users
     */
    async listUsersApiUsersGetRaw(requestParameters: ListUsersApiUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserAsListItem>>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/users/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserAsListItemFromJSON));
    }

    /**
     * List of users.  Requires super user powers.  Args:     limit: Number of users to return. Defaults to 50.     offset: Offset. Defaults to 0.     super_user: Check if current user is super.     user_db: User db.  Returns:     List of users.
     * List Users
     */
    async listUsersApiUsersGet(requestParameters: ListUsersApiUsersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserAsListItem>> {
        const response = await this.listUsersApiUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve profile of currently logged in user.  Args:     user: Current active user.  Returns:     user profile.
     * Profile
     */
    async profileApiUsersProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileInputDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/users/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileInputDTOFromJSON(jsonValue));
    }

    /**
     * Retrieve profile of currently logged in user.  Args:     user: Current active user.  Returns:     user profile.
     * Profile
     */
    async profileApiUsersProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileInputDTO> {
        const response = await this.profileApiUsersProfileGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Users:Current User
     */
    async usersCurrentUserUsersMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/users/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Users:Current User
     */
    async usersCurrentUserUsersMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.usersCurrentUserUsersMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Users:Delete User
     */
    async usersDeleteUserUsersIdDeleteRaw(requestParameters: UsersDeleteUserUsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling usersDeleteUserUsersIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Users:Delete User
     */
    async usersDeleteUserUsersIdDelete(requestParameters: UsersDeleteUserUsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersDeleteUserUsersIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Users:Patch Current User
     */
    async usersPatchCurrentUserUsersMePatchRaw(requestParameters: UsersPatchCurrentUserUsersMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        if (requestParameters.userUpdate === null || requestParameters.userUpdate === undefined) {
            throw new runtime.RequiredError('userUpdate','Required parameter requestParameters.userUpdate was null or undefined when calling usersPatchCurrentUserUsersMePatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/users/me`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateToJSON(requestParameters.userUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Users:Patch Current User
     */
    async usersPatchCurrentUserUsersMePatch(requestParameters: UsersPatchCurrentUserUsersMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.usersPatchCurrentUserUsersMePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Users:Patch User
     */
    async usersPatchUserUsersIdPatchRaw(requestParameters: UsersPatchUserUsersIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling usersPatchUserUsersIdPatch.');
        }

        if (requestParameters.userUpdate === null || requestParameters.userUpdate === undefined) {
            throw new runtime.RequiredError('userUpdate','Required parameter requestParameters.userUpdate was null or undefined when calling usersPatchUserUsersIdPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateToJSON(requestParameters.userUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Users:Patch User
     */
    async usersPatchUserUsersIdPatch(requestParameters: UsersPatchUserUsersIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.usersPatchUserUsersIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Users:User
     */
    async usersUserUsersIdGetRaw(requestParameters: UsersUserUsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRead>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling usersUserUsersIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserReadFromJSON(jsonValue));
    }

    /**
     * Users:User
     */
    async usersUserUsersIdGet(requestParameters: UsersUserUsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRead> {
        const response = await this.usersUserUsersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
