services:
  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ../portal/haddock30.nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      webapp:
        condition: service_started
      backend:
        condition: service_started
    ports:
      - "8180:80"
  webapp:
    image: ghcr.io/i-vresse/haddock3-webapp:${WEBAPP_TAG:-latest}
    build:
      context: ../..
      dockerfile: deploy/Dockerfile
      args:
        HADDOCK3WEBAPP_PREFIX: /haddock30/
    restart: always
    entrypoint: /usr/bin/sh
    command: ["-c", "/wait && npm run setup && npm run start"]
    depends_on:
      bartender:
        condition: service_started
      webappdb:
        condition: service_healthy
      h3restraints:
        condition: service_started
      backend:
        condition: service_started
    environment:
      BARTENDER_API_URL: "http://bartender:8000"
      DATABASE_URL: postgresql://postgres:postgres@webappdb:5432/postgres
      BARTENDER_PRIVATE_KEY: /certs/private_key.pem
      SESSION_SECRET_FILE: /certs/session.secret
      WAIT_PATHS: /certs/private_key.pem
      HADDOCK3_RESTRAINTS_URL: "http://h3restraints:5000"
      HADDOCK3WEBAPP_CSB_PORTAL: active
      HADDOCK3WEBAPP_CSB_PORTAL_BACKEND: http://backend:8180/api
    volumes:
      - bartender-certs:/certs:ro

  backend:
    build:
      context: ../..
      dockerfile_inline: |
        FROM  node:22-bookworm-slim
        WORKDIR /app
        ADD app/mock_portal.ts ./
        RUN npm install cookie
        CMD ["--experimental-strip-types", "mock_portal.ts"]
