version: "3.9"

services:
  bartender:
    volumes:
      - type: bind
        source: ../containerslurm/bartender-config.yaml
        target: /opt/bartender/config.yaml
    depends_on:
      - slurm
  slurm:
    image: ghcr.io/i-vresse/slurm:23
    build:
      context: ..
      dockerfile: containerslurm/Dockerfile
    privileged: true
