import fs from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const h3restraints =
  process.env["HADDOCK3_RESTRAINTS_API_URL"] || "http://localhost:5000";
const mySchema = new URL(`${h3restraints}/openapi.json`);

// Support for `format: binary` see
// https://openapi-ts.pages.dev/node#example-blob-types
const BLOB = ts.factory.createIdentifier("Blob"); // `Blob`
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull()); // `null`
const ast = await openapiTS(mySchema, {
  transform(schemaObject, metadata) {
    if (schemaObject.format === "binary") {
      return schemaObject.nullable
        ? ts.factory.createUnionTypeNode([BLOB, NULL])
        : BLOB;
    }
  },
});

const header = `// This file was generated with "npm run generate-client:restraints" command.
// Do not edit this file manually.

`;

const contents = header + astToString(ast);

const fn = "app/haddock3-restraints-client/schema.d.ts";
fs.writeFileSync(fn, contents);

console.log(`Written ${fn}`);
