name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Fake cns
        run: cp /usr/bin/uptime deploy/cns
      - name: Pull arq deployment
        run: docker compose -f deploy/arq/docker-compose.yml -p playwright pull
      - name: Build arq deployment
        # TODO drop --build-arg once https://github.com/haddocking/haddock3/pull/841 is merged
        run: docker compose -f deploy/arq/docker-compose.yml -p playwright build --build-arg HADDOCK3_VERSION=web-service --build-arg HADDOCK3_GHORG=i-VRESSE
      - name: Run Playwright tests
        run: npx playwright test
